In [ ]:
from google.colab import drive

drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

df_sample = pd.read_csv(
    "/content/drive/MyDrive/SAML-D.csv",
    nrows=10_000,
    dtype={
        "Sender_account": "string",
        "Receiver_account": "string"
    }
)

df_sample.info()
df_sample.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Time                    10000 non-null  object
 1   Date                    10000 non-null  object
 2   Sender_account          10000 non-null  string
 3   Receiver_account        10000 non-null  string
 4   Amount                  10000 non-null  float64
 5   Payment_currency        10000 non-null  object
 6   Received_currency       10000 non-null  object
 7   Sender_bank_location    10000 non-null  object
 8   Receiver_bank_location  10000 non-null  object
 9   Payment_type            10000 non-null  object
 10  Is_laundering           10000 non-null  int64
 11  Laundering_type         10000 non-null  object
dtypes: float64(1), int64(1), object(8), string(2)
memory usage: 937.6+ KB

,Time,Date,Sender_account,Receiver_account,Amount,Payment_currency,Received_currency,Sender_bank_location,Receiver_bank_location,Payment_type,Is_laundering,Laundering_type
0,10:35:19,2022-10-07,8724731955,2769355426,1459.15,UK pounds,UK pounds,UK,UK,Cash Deposit,0,Normal_Cash_Deposits
1,10:35:20,2022-10-07,1491989064,8401255335,6019.64,UK pounds,Dirham,UK,UAE,Cross-border,0,Normal_Fan_Out
2,10:35:20,2022-10-07,287305149,4404767002,14328.44,UK pounds,UK pounds,UK,UK,Cheque,0,Normal_Small_Fan_Out
3,10:35:21,2022-10-07,5376652437,9600420220,11895.00,UK pounds,UK pounds,UK,UK,ACH,0,Normal_Fan_In
4,10:35:21,2022-10-07,9614186178,3803336972,115.25,UK pounds,UK pounds,UK,UK,Cash Deposit,0,Normal_Cash_Deposits

In [ ]:
df_sample["Transaction_timestamp"] = pd.to_datetime(
    df_sample["Date"] + " " + df_sample["Time"],
    format="%Y-%m-%d %H:%M:%S",
    errors="coerce"
)

df_sample[
    ["Date", "Time", "Transaction_timestamp"]
].head()

         Date      Time Transaction_timestamp
0  2022-10-07  10:35:19   2022-10-07 10:35:19
1  2022-10-07  10:35:20   2022-10-07 10:35:20
2  2022-10-07  10:35:20   2022-10-07 10:35:20
3  2022-10-07  10:35:21   2022-10-07 10:35:21
4  2022-10-07  10:35:21   2022-10-07 10:35:21

In [ ]:
df_sample["Transaction_timestamp"].isna().sum()

np.int64(0)

In [ ]:
print(df_sample["Sender_account"].str.len().value_counts())
print(df_sample["Receiver_account"].str.len().value_counts())

print(df_sample["Amount"].describe())

print(df_sample["Is_laundering"].value_counts())

print(df_sample["Payment_type"].value_counts())

print(df_sample["Laundering_type"].value_counts().head(20))

Sender_account
10    9215
9      719
8       63
7        3
Name: count, dtype: Int64
Receiver_account
10    9172
9      773
8       52
7        2
6        1
Name: count, dtype: Int64
count     10000.000000
mean       8378.016667
std       24988.684386
min           9.110000
25%        1961.515000
50%        5824.620000
75%        9818.527500
max      998453.630000
Name: Amount, dtype: float64
Is_laundering
0    9987
1      13
Name: count, dtype: int64
Payment_type
Credit card        2068
ACH                2046
Debit card         2025
Cheque             1989
Cross-border       1042
Cash Deposit        566
Cash Withdrawal     264
Name: count, dtype: int64
Laundering_type
Normal_Small_Fan_Out      3779
Normal_Fan_In             2430
Normal_Fan_Out            1992
Normal_Group               585
Normal_Cash_Deposits       564
Normal_Cash_Withdrawal     264
Normal_Periodical          183
Normal_Mutual               88
Normal_Plus_Mutual          47
Normal_Foward               35
Normal_single_large         20
Structuring                  3
Smurfing                     2
Behavioural_Change_2         2
Layered_Fan_In               2
Cash_Withdrawal              1
Behavioural_Change_1         1
Layered_Fan_Out              1
Scatter-Gather               1
Name: count, dtype: int64